name: flutter_simple_shopify
description: A new Flutter package which provides help in creating a mobile app of a shopify store.
version: 0.0.26-alpha
homepage: https://github.com/ThinkSimple/flutter_simple_shopify

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.0
  freezed_annotation: ^2.2.0
  freezed: 2.1.0+1
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  pedantic: ^1.11.1
